---
ignore: |
  ../workflows/*
  /tmp/lint/.github/workflows/*
  /.github/workflows/*
  /tmp/lint/.github/workflows/deploy.yml
  /tmp/lint/.github/workflows/destroy.yml
  /tmp/lint/.github/workflows/commit-lint.yml
  /tmp/lint/.github/ISSUE_TEMPLATE/bug_report.yml
  /tmp/lint/.github/ISSUE_TEMPLATE/feature_request.yml

extends: default

rules:
  line-length:
    max: 300
    level: warning
  braces:
    max-spaces-inside: 5
