name: Deploy to Azure

on:
  push:
    branches:
      - main
      - feature/*
      - production/*
    tags:        
    - 'v*'

env:
  BUILD_ENVIRONMENT: ${{
    github.ref_type == 'tag' && github.ref_name != 'production/destroy' && 'production' ||
    github.ref_name == 'main' && github.ref_name != 'main/destroy' && 'uat' ||
    startsWith(github.ref_name,  'feature') && github.ref_name != 'feature/destroy' && 'development' }}
  tf_actions_working_dir_init: terraform/prereq
  tf_actions_working_dir: terraform/main

jobs:
  create-container-acr:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.registry_name.outputs.dockerregistry }}
      output2: ${{ steps.registry_name.outputs.resourcegroup }}
      output3: ${{ steps.registry_name.outputs.acrusername }}
      handle: ${{ steps.generate-secret.outputs.handle }}

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir_init }}
    steps:
      - name: Checkout Code for ACR
        uses: actions/checkout@v2
        
      - name: Azure Login action for ACR
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true

      - name: Set up Terraform for ACR
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init for ACR
        run: terraform init
        
      - name: Check and Create Workspace for ACR
        run: |
          if ! terraform workspace list | grep -q "${{ env.BUILD_ENVIRONMENT }}"; then
            terraform workspace new "${{ env.BUILD_ENVIRONMENT }}"
          fi

      - name: Terraform fmt for ACR
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Select Workspace for ACR
        run: terraform workspace select "${{ env.BUILD_ENVIRONMENT }}"

      - name: Terraform Validate for ACR
        run: terraform validate

      - name: Terraform Plan
        run: |
          #!/bin/bash
          # shellcheck disable=SC2086
          set -euo pipefail
          export exitcode=0
          terraform plan -var-file="../../${{ env.BUILD_ENVIRONMENT }}/${{ env.BUILD_ENVIRONMENT  }}.tfvars" \
            -var "container_registry=${{ vars.ACR_NAME }}" \
            -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
          # shellcheck disable=SC2086
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          if [ $exitcode -eq 1 ]; then
            echo "Error: Terraform plan failed"
            exit 1
          else
            echo "Terraform plan was successful"
            exit 0
          fi

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="../../${{ env.BUILD_ENVIRONMENT }}/${{ env.BUILD_ENVIRONMENT  }}.tfvars" \
            -var "container_registry=${{ vars.ACR_NAME }}" \
            -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Get Terraform Registry
        id: registry_name
        run: |
          #!/bin/bash
          set -euo pipefail
          # shellcheck disable=SC2086
          {
            echo "dockerregistry=$(terraform output azurerm_container_registry_name)"
            echo "resourcegroup=$(terraform output azurerm_resource_group_name)"
            echo "acrusername=$(terraform output acr_admin_username)"
          } >> "$GITHUB_OUTPUT"
          echo "$(terraform output acr_admin_password)" | gpg --symmetric --armor --passphrase ${{ secrets.GPG_PASSPHRASE }} >> ~/text


  build-and-push:
    runs-on: ubuntu-latest
    needs: create-container-acr
    outputs:
      output1: ${{ steps.var.outputs.sha_short }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set outputs
        id: var
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: use secret
        id: docpass
        shell: bash
        run: |
          cat ~/text 

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: "${{ needs.create-container-acr.outputs.output1 }}.azurecr.io"
          username: "${{ needs.create-container-acr.outputs.output3 }}"
          password: cat ~/text|gpg --decrypt --passphrase ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ needs.create-container-acr.outputs.output1 }}.azurecr.io/my-app-${{ env.BUILD_ENVIRONMENT }}:"${{ steps.var.outputs.sha_short }}" --target ${{ env.BUILD_ENVIRONMENT }} .
          docker push ${{ needs.create-container-acr.outputs.output1 }}.azurecr.io/my-app-${{ env.BUILD_ENVIRONMENT }}:"${{ steps.var.outputs.sha_short }}"

  terraform:
    runs-on: ubuntu-latest
    needs: [ build-and-push, create-container-acr ]
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        
      - name: Check and Create Workspace
        run: |
          if ! terraform workspace list | grep -q "${{ env.BUILD_ENVIRONMENT }}"; then
            terraform workspace new "${{ env.BUILD_ENVIRONMENT }}"
          fi

      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Select Workspace
        run: terraform workspace select "${{ env.BUILD_ENVIRONMENT }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Display short commit
        run: echo "$sha_short"

      - name: Terraform Plan
        run: |
          #!/bin/bash
          # shellcheck disable=SC2086
          set -euo pipefail
          export exitcode=0
          terraform plan -var-file="../../${{ env.BUILD_ENVIRONMENT }}/${{ env.BUILD_ENVIRONMENT  }}.tfvars" \
            -var "acr_name=${{ needs.create-container-acr.outputs.output1 }}" \
            -var "acr_login_url=https://${{ needs.create-container-acr.outputs.output1 }}.azureecr.io" \
            -var "docker_image_name=my-app-${{ env.BUILD_ENVIRONMENT }}:${{ needs.build-and-push.outputs.output1 }}" \
            -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var "app_azurerm_rg=${{ needs.create-container-acr.outputs.output2 }}"

          # shellcheck disable=SC2086
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          if [ $exitcode -eq 1 ]; then
            echo "Error: Terraform plan failed"
            exit 1
          else
            echo "Terraform plan was successful"
            exit 0
          fi

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="../../${{ env.BUILD_ENVIRONMENT }}/${{ env.BUILD_ENVIRONMENT  }}.tfvars" \
            -var "acr_name=${{ needs.create-container-acr.outputs.output1 }}" \
            -var "acr_login_url=https://${{ needs.create-container-acr.outputs.output1 }}.azurecr.io" \
            -var "docker_image_name=my-app-${{ env.BUILD_ENVIRONMENT }}:${{ needs.build-and-push.outputs.output1 }}" \
            -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var "app_azurerm_rg=${{ needs.create-container-acr.outputs.output2 }}"
     
      - name: validate endpoint of webapp
        run: |
          #!/bin/bash
          # shellcheck disable=SC2086
          set -euo pipefail
          part1="https://"
          part2=$(terraform output azurerm_container_app_url)
          # shellcheck disable=SC2086
          echo "part2: $part2"
          # shellcheck disable=SC2086
          part3=$(echo $part2|sed -e 's/^"//' -e 's/"$//')
          # shellcheck disable=SC2086
          requestURL=$part1$part3
          echo "requestURL: $requestURL"
          # shellcheck disable=SC2086
          statuscode=$(eval "curl -s -o /dev/null -w '%{http_code}' $requestURL")
          # shellcheck disable=SC2086
          echo "statuscode: $statuscode"
          # shellcheck disable=SC2086
          if [ $statuscode -ne 200 ]; then
            echo "Error: Endpoint didn't work"
            exit 1
          else
            echo "Webapp deployment and test was successful"
            exit 0
          fi
