name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.11.0'

    - name: Install dependencies
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install @semantic-release/changelog -D
        npm install @semantic-release/git -D
        npm install @semantic-release/exec -D
        npx semantic-release@24
